layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
      - wwdda.github.io
      - github-slideshow
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
    facebook: 100022567502246
  # hackerrank: your_username
    instagram: andywwway
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
    youtube: channel/UC6B8cN7vJp5lQrMv4QIB-tQ
  # website: http://vsco.co/andywwway

topics:
  - name: Running
    web_url: https://show.gotokeep.com/users/5d98d22855bcc461489deed4?utm_source=others&utm_medium=web&utm_campaign=client_share&utm_term=&utm_content=users
    image_url: http://m.qpic.cn/psc?/d0149cad-9963-4ee6-a2e6-671ffcca4dfe/ZFhS36rpk9iEVIe7oh2lYp0VIUvpvomLt1UmKEwYtqBwN0VUZEFcN4TQE4KagmpZzAl4JDMD1B1XHowkoC5iT8N9aarcHlcTkIdgNk8Vn5E!/b&bo=AAIAAgAAAAADByI!&rf=viewer_4

  - name: Photography
    web_url: http://vsco.co/andywwway
    image_url: http://m.qpic.cn/psc?/d0149cad-9963-4ee6-a2e6-671ffcca4dfe/ZFhS36rpk9iEVIe7oh2lYppzG.oy0uJ3ArjtULIrgfSYGDQ32eMDvDnhyqoi*qEeyuQHNWv4izUUbow7cJ5jXDjnbZ2Wy1XB4qBWHKbVePY!/b&bo=lgCWAAAAAAADFzI!&rf=viewer_4

  - name: Algorithm
    web_url: https://github.com/topics/algorithm
    image_url: http://m.qpic.cn/psc?/d0149cad-9963-4ee6-a2e6-671ffcca4dfe/ZFhS36rpk9iEVIe7oh2lYhJEljIJ*8T8njUEMqjWZ8RkPb0J*NDdMtnmyvfssLOJGMjQjF9c9s5skOutE0v0u4Ar.78mYMJpKs0s6k3dxL4!/b&bo=AAQABAAAAAADFzI!&rf=viewer_4
